encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/new", views.create_entry, name="createEntry"),
    path("wiki/random", views.random_entry, name="randomEntry"),
    path("wiki/search", views.search_entries, name="searchEntries"),
    path("wiki/<title>", views.get_entry, name="getEntry"),
    path("wiki/<title>/edit", views.edit_entry, name="editEntry"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")),
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/forms/add_entry.py
from django import forms

class AddEntryForm(forms.Form):
    title = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Title"}), label_suffix='', label='')
    content = forms.CharField(widget=forms.Textarea(attrs={"cols": 30, "rows": 15, "class": "form-control", "placeholder": "Content.."}), required=True, label_suffix='', label='')

encyclopedia/views.py
from django.http.request import QueryDict
from django.shortcuts import redirect, render
from django.urls import reverse
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt

from . import util
import markdown2
from .forms.add_entry import AddEntryForm
# from random import randint
import random


def index(req):
    entries = util.list_entries()
    entries_len = len(entries)
    return render(req, "encyclopedia/index.html", {"entries_len": entries_len, "entries": entries})


def get_entry(req, title):
    ctx = {
        "title": title,
        "content": markdown2.markdown(util.get_entry(title))
        if util.get_entry(title)
        else None,
    }
    return render(req, "encyclopedia/entry_details.html", ctx)


def create_entry(req):

    if req.method == "POST":
        form = AddEntryForm(req.POST)
        if form.is_valid():
            try:

                ctx = {"form": form}

                # is exists
                is_exists = util.get_entry(form.cleaned_data["title"])
                if is_exists:
                    messages.error(
                        req, "Entry Already Exists!", "danger", fail_silently=True
                    )
                    return render(req, "encyclopedia/add_entry.html", ctx)

                #  save
                util.save_entry(
                    form.cleaned_data["title"], form.cleaned_data["content"]
                )
                messages.success(
                    req, "Saved Successfully", "success", fail_silently=True
                )
                return redirect(
                    reverse(
                        "encyclopedia:getEntry",
                        kwargs={"title": form.cleaned_data["title"]},
                    )
                )

            except Exception as er:
                messages.error(req, er, "danger", fail_silently=True)

        return render(req, "encyclopedia/add_entry.html", ctx)
    
    else:
        form = AddEntryForm()
        ctx = {"form": form, "title": "Create New"}
        return render(req, "encyclopedia/add_entry.html", ctx)


def edit_entry(req, title):

    if req.method == "POST":
        request = QueryDict(f'title={title}&content={req.POST["content"]}').copy()
        form = AddEntryForm(request)
        ctx = {"form": form, "title": title}
        if form.is_valid():
            try:

                #  save
                util.save_entry(
                    title, form.cleaned_data["content"]
                )
                messages.success(
                    req, "Updated Successfully", "success", fail_silently=True
                )
                return redirect(
                    reverse(
                        "encyclopedia:getEntry",
                        kwargs={"title": title},
                    )
                )

            except Exception as er:
                messages.error(req, er, "danger", fail_silently=True)

        return render(req, "encyclopedia/edit_entry.html", ctx)
    
    else:
        form = AddEntryForm()
        # set initial values
        form.initial = {
            "content": util.get_entry(title)
        }
        ctx = {"form": form, "title": title}
        
        return render(req, "encyclopedia/edit_entry.html", ctx)


def random_entry(req):
    entries = util.list_entries()
    li_len = len(entries)

    if not li_len:
        messages.error(req, "No Entries Yet!", "danger", fail_silently=True)
        return render(req, "encyclopedia/index.html")

    # rand_entry = entries[randint(0, li_len - 1)]
    rand_entry = random.choice(entries)

    ctx = {
        "title": rand_entry,
        "content": markdown2.markdown(util.get_entry(rand_entry))
        if util.get_entry(rand_entry)
        else None,
    }
    return render(req, "encyclopedia/entry_details.html", ctx)

@csrf_exempt
def search_entries(req):
    q = req.GET.get("q")
    if not q:
        return render(req, "encyclopedia/search.html")

    try:
        entries = util.search_entry(q)
        if not entries:
            return render(req, "encyclopedia/search.html")

        return render(req, "encyclopedia/search.html", {"results": entries, "q": q})
    
    except Exception as er:
        messages.error(req, er, "danger", fail_silently=True)
        return render(req, "encyclopedia/search.html")

encyclopedia/templates/encyclopedia/add_entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}
    <div class="content-wrapper d-flex justify-content-between align-items-start flex-wrap shadow my-4 p-4">
        <h1>Create Entry</h1>
        <div class="row w-100">
            <div class="col-md-10 h-100">
                <form action="{% url 'encyclopedia:createEntry' %}" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input class="btn btn-primary" type="submit" value="Save">
                </form>
            </div>
        </div>
    </div>

{% endblock %}

encyclopedia/templates/encyclopedia/edit_entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}
    <div class="content-wrapper d-flex justify-content-between align-items-start flex-wrap shadow my-4 p-4">
        <div class="row w-100">
            <div class="col-md-10 h-100">
                <h1>Edit {{title}}</h1>
                {% if form.content %}
                    <form action="{% url 'encyclopedia:editEntry' title %}" method="post">
                        {% csrf_token %}
                        <p>
                            {{ form.content }}
                        </p>
                        <input class="btn btn-primary" type="submit" value="Save">
                    </form>
                {% else %}
                    <div class="text-center mx-auto">
                        <h1>{{title}}</h1>
                        <strong>404 Not Found</strong>
                        <p>
                            <span>No Content for this Entry!</span>
                        </p>
                        <a role="button" class="btn btn-outline-primary" href="{% url 'encyclopedia:createEntry' %}">Create One</a>
                        <a role="button" class="btn btn-outline-secondary" href="{% url 'encyclopedia:index' %}">Home</a>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

encyclopedia/templates/encyclopedia/entry_details.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}

    <div class="content-wrapper d-flex justify-content-between align-items-start shadow my-4 p-4">
        {% if content %}
            {% comment %} <h1>{{title}}</h1> {% endcomment %}
            <div class="content">
                {{content|safe}}
            </div>
            <a role="button" class="btn btn-outline-primary" href="{% url 'encyclopedia:editEntry' title %}">Edit</a>
        {% else %}
            <div class="text-center mx-auto">
                <h1>{{title}}</h1>
                <strong>404 Not Found</strong>
                <p>
                    <span>No Content for this Entry!</span>
                </p>
                <a role="button" class="btn btn-outline-primary" href="{% url 'encyclopedia:createEntry' %}">Create One</a>
                <a role="button" class="btn btn-outline-secondary" href="{% url 'encyclopedia:index' %}">Home</a>
            </div>
        {% endif %}
    </div>


{% endblock %}

encyclopedia/templates/encyclopedia/includes/side_nav.html
<h2>Wiki</h2>
<form action="{% url 'encyclopedia:searchEntries' %}" method="GET">
    {% comment %} {% csrf_token %} {% endcomment %}
    <input class="search form-control" type="text" name="q" placeholder="Search Encyclopedia">
</form>

<div class="list-group mt-4">
    {% url 'encyclopedia:index' as index %}
    {% url 'encyclopedia:createEntry' as createEntry %}
    {% url 'encyclopedia:randomEntry' as randomEntry %}
    
    <a 
        href="{% url 'encyclopedia:index' %}" 
        class="list-group-item list-group-item-action d-flex justify-content-between align-items-center {% if request.path == index %} active {% endif %}" 
    >
        Home
        {% comment %} <span class="badge bg-danger rounded-pill">{{entries_len}}</span> {% endcomment %}
    </a>
    <a href="{% url 'encyclopedia:createEntry' %}" class="list-group-item list-group-item-action {% if request.path == createEntry %} active {% endif %}">Create New Page</a>
    <a href="{% url 'encyclopedia:randomEntry' %}" class="list-group-item list-group-item-action {% if request.path == randomEntry %} active {% endif %}">Random Page</a>
</div>

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
<div class="d-flex justify-content-start align-items-start py-3">
    <h1 class="m-0 p-0">All Pages</h1>
    <span class="badge bg-danger rounded-pill">{{entries_len}}</span>
</div>

    <div class="content-wrapper d-flex justify-content-between align-items-start flex-wrap shadow my-4 p-4">
        <div class="row row-cols-1 row-cols-md-4 g-4 mt-4">
            {% if entries %}
                {% for entry in entries %}
                        <div class="col">
                            <div class="card">
                                <div class="card-body d-flex justify-content-between align-items-center">
                                    <h5 class="card-title m-0">
                                        <a role="link" class="text-decoration-none" href="{% url 'encyclopedia:getEntry' entry %}">{{entry}}</a>
                                    </h5>
                                    <p class="card-text m-0">
                                        <a role="link" class="btn btn-outline-info rounded-pill btn-sm" href="{% url 'encyclopedia:getEntry' entry %}">View</a>
                                        <a role="link" class="btn btn-outline-primary rounded-pill btn-sm" href="{% url 'encyclopedia:editEntry' entry %}">Edit</a>
                                    </p>
                                </div>
                            </div>
                        </div>
                {% endfor %}
            {% else %}
                <div class="text-center">
                    <h4>No Entries Yet</h4>
                    <a role="button" class="btn btn-outline-primary" href="{% url 'encyclopedia:createEntry' %}">Create One</a>
                </div>
            {% endif %}
        </div>
    </div>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>Wiki | {% block title %}{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">        
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                {% include "./includes/side_nav.html" %}
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                <div class="container">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                                <strong>{{ message }}</strong>
                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close" onclick="this.parentElement.remove()"></button>
                            </div>
                        {% endfor %}
                    {% endif %}

                    {% block body %}
                    {% endblock %}
                </div>
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

    <div class="content-wrapper search-page d-flex justify-content-start align-items-center flex-wrap flex-column shadow my-4 p-4">
        <div class="row w-100">
            <div class="col-d-12 d-flex justify-content-between align-items-center flex-wrap w-100">
                <h4 class="m-0 p-0">Search Results for: {{q}}</h4> 
                {% if results %} 
                    <span class="badge bg-danger rounded-pill">{{results|length}}</span>
                {% endif %}
            </div>
        </div>
        {% if results %}
            <div class="row w-100 mt-4">
                <div class="col-md-12">
                    <div class="card">
                        {% for entry in results %}
                            {% url 'encyclopedia:getEntry' entry.title as url %}
                            <div class="card-body {% if results|length > 1 and forloop.counter != results|length %}border-bottom{% endif %}">
                                <p class="m-0">{% if request.is_secure %}https://{% else %}http://{% endif %}{{request.get_host}} > {{url}}</p>
                                <a class="d-inline-block" href="{{url}}">
                                    <h5 class="card-title">{{entry.title}}</h5>
                                </a>
                                <p class="card-text m-0">
                                    {{entry.content|truncatechars:50}}
                                </p>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% else %}
                <div class="text-center w-100">
                    <h4>No Results!</h4>
                </div>
            </div>
        {% endif %}
    </div>

{% endblock %}